version: '3.8'
services:

  ### ----------------------- Spring Boot Backend ----------------------- ###
  imdb-clone-backend:
    container_name: imdb-clone-backend
    image: niklastiede/imdb-clone-backend:latest
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - backend_address_prod=${BACKEND_APP_ADDRESS_ENV_VAR}
      - frontend_address_prod=${FRONTEND_APP_ADDRESS_ENV_VAR}
      - mysql_username_prod=${MYSQL_USERNAME_ENV_VAR}
      - mysql_password_prod=${MYSQL_PASSWORD_ENV_VAR}
      - enable_mail_prod=false
      - mail_username_prod=${MAIL_USERNAME_ENV_VAR}
      - mail_password_prod=${MAIL_PASSWORD_ENV_VAR}
      - elasticsearch_username_prod=${ELASTIC_USERNAME_ENV_VAR}
      - elasticsearch_password_prod=${ELASTIC_PASSWORD_ENV_VAR}
      - minio_access_key_prod=${MINIO_ACCESS_KEY_ENV_VAR}
      - minio_secret_key_prod=${MINIO_SECRET_KEY_ENV_VAR}
      - jwt_secret_prod=${JWT_SECRET_ENV_VAR}
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - imdb-clone-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.imdb-clone.the-coding-lab.com`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls.certresolver=myresolver"

  ### ----------------------- React Frontend ----------------------- ###
  imdb-clone-frontend:
    container_name: imdb-clone-frontend
    image: niklastiede/imdb-clone-frontend:latest
    restart: always
    environment:
      - REACT_APP_IMDB_CLONE_BACKEND_ADDRESS=${BACKEND_APP_ADDRESS_ENV_VAR}
      - REACT_APP_IMDB_CLONE_MINIO_ADDRESS=${MINIO_ADDRESS_ENV_VAR}
    networks:
      - imdb-clone-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`imdb-clone.the-coding-lab.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"

  ## ----------------------- Reverse Proxy ----------------------- ###
  imdb-clone-reverse-proxy:
    image: traefik:latest
    container_name: imdb-clone-reverse-proxy
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.email=niklastiede2@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./acme.json:/acme.json
    networks:
      - imdb-clone-network

networks:
  imdb-clone-network:
    name: imdb-clone-network
    external: true
