version: '3.8'
services:

  ### ----------------------- Spring Boot Backend ----------------------- ###
  imdb-clone-backend:
    container_name: imdb-clone-backend
    image: niklastiede/imdb-clone-backend:latest
    restart: always
    environment:
      - IMDB_CLONE_BACKEND_HOST=http://robotnik-um560:8080
      - IMDB_CLONE_FRONTEND_HOST=http://robotnik-um560:80
      - SPRING_DATASOURCE_URL=jdbc:mysql://imdb-clone-mysql:3306/movie_db?serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME_ENV_VAR}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD_ENV_VAR}
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=false
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME_ENV_VAR}
      - SPRING_MAIL_PASSWORD=${MAIL_PASSWORD_ENV_VAR}
      - SPRING_ELASTICSEARCH_REST_URIS=imdb-clone-elasticsearch:9200
      - SPRING_ELASTICSEARCH_USERNAME=${ELASTIC_USERNAME_ENV_VAR}
      - SPRING_ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD_ENV_VAR}
      - MINIO_REST_URI=http://imdb-clone-minio:9000
      - MINIO_REST_ACCESSKEY=${MINIO_ACCESS_KEY_ENV_VAR}
      - MINIO_REST_SECRETKEY=${MINIO_SECRET_KEY_ENV_VAR}
      - JWT_EXPIRATION_IN_MS=2592000000
      - CORS_ALLOWED_ORIGINS${FRONTEND_APP_ADDRESS_ENV_VAR}
    ports:
      - "8080:8080"
    networks:
      - imdb-clone-network

  ### ----------------------- React Frontend ----------------------- ###
  imdb-clone-frontend:
    container_name: imdb-clone-frontend
    image: niklastiede/imdb-clone-frontend:latest
    restart: always
    environment:
      - REACT_APP_IMDB_CLONE_BACKEND_APP_ADDRESS_DOCKER=${BACKEND_APP_ADDRESS_ENV_VAR}
    ports:
      - "80:80"
    networks:
      - imdb-clone-network

networks:
  imdb-clone-network:
    name: imdb-clone-network
    external: true
