openapi: 3.0.3
info:
  title: IMDB Backend Clone for Movie and User Data
  version: v1
servers:
  - url: http://{environment}
    description: the host of movies service
    variables:
      environment:
        default: localhost:8080
        enum:
          - localhost:8080         # localhost
          - some-url-int.de        # integration-k8s
paths:
  /movie/{movieId}:
    get:
      tags:
        - movies
      summary: Gets MovieDto by movieId
      operationId: getMovieById
      parameters:
        - name: movieId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieDto'
        "400":
          description: Client error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientErrorsResponse'
        "500":
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerErrorResponse'

components:
  schemas:

#    SalesPartnersByPermissionsRequest:
#      type: object
#      properties:
#        groupId:
#          type: integer
#          format: int32
#        permissions:
#          type: array
#          items:
#            type: integer
#            format: int64
#
#    SharedSalesPartnerResponse:
#      type: object
#      additionalProperties:
#        type: array
#        items:
#          $ref: '#/components/schemas/MovieDto'

    MovieDto:
      type: object
      properties:
        movieId:
          type: integer
          format: int32
        title:
          type: string
        year:
          type: string

    ClientError:
      type: object
      properties:
        code:
          type: string
        messageKey:
          type: string
        messageText:
          type: string
        fields:
          type: array
          items:
            type: string
        debug:
          type: string

    ClientErrorsResponse:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ClientError'

    ServerErrorResponse:
      type: object
      properties:
        code:
          type: string
        debug:
          type: string
        stacktrace:
          type: string

  securitySchemes:
    API-key:
      type: apiKey
      name: api-key
      in: header

security:
  - API-key: []



