services:

  ### ----------------------- PostgreSQL ----------------------- ###
  imdb-clone-postgresql:
    container_name: imdb-clone-postgresql
    image: postgres:18
    restart: unless-stopped
    environment:
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=myroot
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - imdb-clone-postgresql-data:/var/lib/postgresql
    networks:
      - imdb-clone-network

  imdb-clone-elasticsearch:
    container_name: imdb-clone-elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:9.3.4
    restart: unless-stopped
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx2g
    ports:
      - "9200:9200"
    volumes:
      - imdb-clone-elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - imdb-clone-network

  ### ----------------------- RustFS ----------------------- ###
  imdb-clone-rustfs:
    container_name: imdb-clone-rustfs
    image: rustfs/rustfs:1.0.0-beta.2
    restart: unless-stopped
    user: root
    environment:
      - RUSTFS_ACCESS_KEY=ROOTNAME
      - RUSTFS_SECRET_KEY=CHANGEME123
      - RUSTFS_CONSOLE_ENABLE=true
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - imdb-clone-rustfs-data:/data
    networks:
      - imdb-clone-network
    command: /data

  imdb-clone-seed-light:
    image: ${IMDB_CLONE_SEED_LIGHT_IMAGE:-niklastiede/imdb-clone-seed:light-local}
    profiles:
      - seed-light
    depends_on:
      - imdb-clone-postgresql
      - imdb-clone-rustfs
    environment:
      - POSTGRES_HOST=imdb-clone-postgresql
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=myroot
      - POSTGRES_PASSWORD=secret
      - RUSTFS_ENDPOINT=http://imdb-clone-rustfs:9000
      - RUSTFS_ACCESS_KEY=ROOTNAME
      - RUSTFS_SECRET_KEY=CHANGEME123
      - RUSTFS_BUCKET=imdb-clone
      - SEED_NAME=light
      - SEED_VERSION=${SEED_VERSION:-local}
    networks:
      - imdb-clone-network

  imdb-clone-seed-full:
    image: ${IMDB_CLONE_SEED_FULL_IMAGE:-niklastiede/imdb-clone-seed:full-local}
    profiles:
      - seed-full
    depends_on:
      - imdb-clone-postgresql
      - imdb-clone-rustfs
    environment:
      - POSTGRES_HOST=imdb-clone-postgresql
      - POSTGRES_DB=movie_db
      - POSTGRES_USER=myroot
      - POSTGRES_PASSWORD=secret
      - RUSTFS_ENDPOINT=http://imdb-clone-rustfs:9000
      - RUSTFS_ACCESS_KEY=ROOTNAME
      - RUSTFS_SECRET_KEY=CHANGEME123
      - RUSTFS_BUCKET=imdb-clone
      - SEED_NAME=full
      - SEED_VERSION=${SEED_VERSION:-local}
    networks:
      - imdb-clone-network

volumes:
  imdb-clone-postgresql-data:
    name: imdb-clone-postgresql-data
  imdb-clone-elasticsearch-data:
    name: imdb-clone-elasticsearch-data
  imdb-clone-rustfs-data:
    name: imdb-clone-rustfs-data

networks:
  imdb-clone-network:
    name: imdb-clone-network
    driver: bridge
