
#version: '3'
#
#services:
#  postgres:
#    image: postgres:13.1
#    healthcheck:
#      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
#      timeout: 45s
#      interval: 10s
#      retries: 10
#    restart: always
#    environment:
#      - POSTGRES_USER=root
#      - POSTGRES_PASSWORD=password
#      - APP_DB_USER=docker
#      - APP_DB_PASS=docker
#      - APP_DB_NAME=docker
#    ports:
#      - "5432:5432"



#version: "3"
#services:
##  imdb:
##    image: imdb
##    ports:
##      - "3306:3306"
##    networks:
##      - movies-mysql
#
#  mysqldb:
#    image: mysql:latest
##    networks:
##      - movies-mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=root
#      - MYSQL_DATABASE=bootdb





version: '3.3'
services:
  my-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db:
    driver: local





