SET FOREIGN_KEY_CHECKS = 0;
SET UNIQUE_CHECKS = 0;

LOAD DATA INFILE '/tmp/proc_imdb_movies.00001.csv' IGNORE

    INTO TABLE IMDBCLONE.MOVIE
    FIELDS TERMINATED BY ','
    ENCLOSED BY '"'
    LINES TERMINATED BY '\n'
    (ID,MOVIE_TYPE,PRIMARY_TITLE,ORIGINAL_TITLE,IS_ADULT,START_YEAR,END_YEAR,RUNTIME_MINUTES,MOVIE_GENRE,IMDB_RATING,IMDB_RATING_COUNT);

SET UNIQUE_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 1;
