
### get current user
GET {{protocol}}{{host}}:{{port}}/api/account/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInN1YiI6IjEiLCJpYXQiOjE2NzIwOTM0NDUsImV4cCI6MTY3NDY4NTQ0NX0.zsJCJZcMAP87dHfOLXHmjJs7w7TRs7Ldemv4EWZseM6Ki9oJV5ukGEJJweVPjxc0fcdP4Yx0YrDrsMKBox5Zyg


### get account-profile
GET {{protocol}}{{host}}:{{port}}/api/account/superman/profile
Content-Type: application/json


### get comments of user
GET {{protocol}}{{host}}:{{port}}/api/account/superman/comments?page=0&size=10
Content-Type: application/json


### get watchlist of user
GET {{protocol}}{{host}}:{{port}}/api/account/superman/watchlist
Content-Type: application/json


### get ratings of user
GET {{protocol}}{{host}}:{{port}}/api/account/superman/ratings
Content-Type: application/json


### update account data
PUT {{protocol}}{{host}}:{{port}}/api/account/superman
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInN1YiI6IjEiLCJpYXQiOjE2NzIwOTM0NDUsImV4cCI6MTY3NDY4NTQ0NX0.zsJCJZcMAP87dHfOLXHmjJs7w7TRs7Ldemv4EWZseM6Ki9oJV5ukGEJJweVPjxc0fcdP4Yx0YrDrsMKBox5Zyg
Content-Type: application/json

{
  "firstName": "Kermit",
  "lastName": "The Frog",
  "phone": "0152/8273654",
  "bio": "I like to swim.",
  "birthday": "1995-01-25T00:00:00.000"
}


### delete account
DELETE {{protocol}}{{host}}:{{port}}/api/account/superman
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNjY0NDczODU4LCJleHAiOjE2NjcwNjU4NTh9.ETAhhVOlArJFdUVV1TsFO9xiEeUCICeorW19lZIgwtZeCS_qx_wrCL7sgcZjjrCb0IxO8pQWTvos9hXYZtF8JA
Content-Type: application/json


### create new account, without email confirmation (simple test acc generation)
POST {{protocol}}{{host}}:{{port}}/api/account/add-account
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNjY0NDczODU4LCJleHAiOjE2NjcwNjU4NTh9.ETAhhVOlArJFdUVV1TsFO9xiEeUCICeorW19lZIgwtZeCS_qx_wrCL7sgcZjjrCb0IxO8pQWTvos9hXYZtF8JA
Content-Type: application/json

{
  "username": "TheIncredibleHulk",
  "email": "MisterX@gmail.com",
  "password": "Str0ng!Pa55Word",
  "firstName": "Kermit",
  "lastName": "The Frog"
}


### give account ADMIN permission
PUT {{protocol}}{{host}}:{{port}}/api/account/TheIncredibleHulk/give-admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNjY0NDczODU4LCJleHAiOjE2NjcwNjU4NTh9.ETAhhVOlArJFdUVV1TsFO9xiEeUCICeorW19lZIgwtZeCS_qx_wrCL7sgcZjjrCb0IxO8pQWTvos9hXYZtF8JA
Content-Type: application/json


### remove ADMIN permission of an account
PUT {{protocol}}{{host}}:{{port}}/api/account/TheIncredibleHulk/take-admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNjY0NDczODU4LCJleHAiOjE2NjcwNjU4NTh9.ETAhhVOlArJFdUVV1TsFO9xiEeUCICeorW19lZIgwtZeCS_qx_wrCL7sgcZjjrCb0IxO8pQWTvos9hXYZtF8JA
Content-Type: application/json
