
### get current user
GET {{protocol}}{{host}}:{{port}}/api/account/me
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibGVzX2dyb3NzbWFuIiwic3ViIjoiMSIsImlhdCI6MTcxMTg0NDYyNCwiZXhwIjoxNzE0NDM2NjI0fQ.KAlfHvE4GsmBnGqzUxxMmO1FaJo5mfctTa5zlJQ-0gKsUOopgZWuaUkEMO5h92QnLQQzFYy8doQqXRgTC9kMvg


### get account-profile
GET {{protocol}}{{host}}:{{port}}/api/account/les_grossman/profile
Content-Type: application/json


### get comments of user
GET {{protocol}}{{host}}:{{port}}/api/account/les_grossman/comments?page=0&size=10
Content-Type: application/json


### get watchlist of user
GET {{protocol}}{{host}}:{{port}}/api/account/les_grossman/watchlist
Content-Type: application/json


### get ratings of user
GET {{protocol}}{{host}}:{{port}}/api/account/les_grossman/ratings
Content-Type: application/json


### update account data
PUT {{protocol}}{{host}}:{{port}}/api/account/kirk_lazarus
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibGVzX2dyb3NzbWFuIiwic3ViIjoiMSIsImlhdCI6MTcxMTg0NDYyNCwiZXhwIjoxNzE0NDM2NjI0fQ.KAlfHvE4GsmBnGqzUxxMmO1FaJo5mfctTa5zlJQ-0gKsUOopgZWuaUkEMO5h92QnLQQzFYy8doQqXRgTC9kMvg
Content-Type: application/json

{
  "firstName": "Kirk",
  "lastName": "Lazarus",
  "phone": "0152/8273654",
  "bio": "Man, I don't drop character 'till I done the DVD commentary.",
  "birthday": "1965-04-04T00:00:00.000"
}


### delete account
DELETE {{protocol}}{{host}}:{{port}}/api/account/kirk_lazarus
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibGVzX2dyb3NzbWFuIiwic3ViIjoiMSIsImlhdCI6MTcxMTg0NDYyNCwiZXhwIjoxNzE0NDM2NjI0fQ.KAlfHvE4GsmBnGqzUxxMmO1FaJo5mfctTa5zlJQ-0gKsUOopgZWuaUkEMO5h92QnLQQzFYy8doQqXRgTC9kMvg
Content-Type: application/json


### create new account, without email confirmation (simple test acc generation)
POST {{protocol}}{{host}}:{{port}}/api/account/add-account
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibGVzX2dyb3NzbWFuIiwic3ViIjoiMSIsImlhdCI6MTcxMTg0NDYyNCwiZXhwIjoxNzE0NDM2NjI0fQ.KAlfHvE4GsmBnGqzUxxMmO1FaJo5mfctTa5zlJQ-0gKsUOopgZWuaUkEMO5h92QnLQQzFYy8doQqXRgTC9kMvg
Content-Type: application/json

{
  "username": "kirk_lazarus",
  "email": "kirk.lazarus@gmail.com",
  "password": "Encrypted!Pa55worD"
}


### give account ADMIN permission
PUT {{protocol}}{{host}}:{{port}}/api/account/kirk_lazarus/give-admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibGVzX2dyb3NzbWFuIiwic3ViIjoiMSIsImlhdCI6MTcxMTg0NDYyNCwiZXhwIjoxNzE0NDM2NjI0fQ.KAlfHvE4GsmBnGqzUxxMmO1FaJo5mfctTa5zlJQ-0gKsUOopgZWuaUkEMO5h92QnLQQzFYy8doQqXRgTC9kMvg
Content-Type: application/json


### remove ADMIN permission of an account
PUT {{protocol}}{{host}}:{{port}}/api/account/kirk_lazarus/take-admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibGVzX2dyb3NzbWFuIiwic3ViIjoiMSIsImlhdCI6MTcxMTg0NDYyNCwiZXhwIjoxNzE0NDM2NjI0fQ.KAlfHvE4GsmBnGqzUxxMmO1FaJo5mfctTa5zlJQ-0gKsUOopgZWuaUkEMO5h92QnLQQzFYy8doQqXRgTC9kMvg
Content-Type: application/json
