
### check username availability
GET {{protocol}}{{host}}:{{port}}/api/auth/check-username-availability?username=notusedusername
Content-Type: application/json


### check email availability
GET {{protocol}}{{host}}:{{port}}/api/auth/check-email-availability?email=notused@gmail.com
Content-Type: application/json


### login
POST {{protocol}}{{host}}:{{port}}/api/auth/login
Content-Type: application/json

{
  "usernameOrEmail": "superman",
  "password": "Str0nG!Pa55Word?"
}


### register
POST {{protocol}}{{host}}:{{port}}/api/auth/registration
Content-Type: application/json

{
  "username": "superman",
  "password": "Str0nG!Pa55Word?",
  "email": "your@email.com"
}


### confirm email token
GET {{protocol}}{{host}}:{{port}}/api/auth/confirm-email-address?token=a32f1eaa-7b1a-4015-9b27-bf8d6e0bcaf0
Content-Type: application/json


### reset password
GET {{protocol}}{{host}}:{{port}}/api/auth/reset-password?email=niklastiede2@gmail.com
Content-Type: application/json


### save new password
POST {{protocol}}{{host}}:{{port}}/api/auth/save-new-password
Content-Type: application/json

{
  "token": "4a4e73e5-54cb-4e8f-8c42-40fd1e1adc54",
  "newPassword": "Th1s.Is.Str0ng!"
}
