
### store movie image
POST {{protocol}}{{host}}:{{port}}/api/file-storage/movie/48812
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInN1YiI6IjEiLCJpYXQiOjE2NzkzMDUzMDAsImV4cCI6MTY4MTg5NzMwMH0.wZTqM6p69J1DSrtO3bpLgc5yPVm8dWTffHTHT3lF5E8y9Qn4vK5JZeiD5yeGXxOc-FZy3cdauiZGpbCi74R4uA
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="raw-movie-image.jpg"

< ./minio/raw-movie-image.jpg
--boundary--


### delete movie image
DELETE {{protocol}}{{host}}:{{port}}/api/file-storage/movie/48812
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInN1YiI6IjEiLCJpYXQiOjE2NzkzMDUzMDAsImV4cCI6MTY4MTg5NzMwMH0.wZTqM6p69J1DSrtO3bpLgc5yPVm8dWTffHTHT3lF5E8y9Qn4vK5JZeiD5yeGXxOc-FZy3cdauiZGpbCi74R4uA


### store user profile photo
POST {{protocol}}{{host}}:{{port}}/api/file-storage/profile-photo
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInN1YiI6IjEiLCJpYXQiOjE2NzkzMDUzMDAsImV4cCI6MTY4MTg5NzMwMH0.wZTqM6p69J1DSrtO3bpLgc5yPVm8dWTffHTHT3lF5E8y9Qn4vK5JZeiD5yeGXxOc-FZy3cdauiZGpbCi74R4uA
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="raw-profile-photo.jpeg"

< ./minio/raw-profile-photo.jpeg
--boundary--


### delete user profile photo
DELETE {{protocol}}{{host}}:{{port}}/api/file-storage/profile-photo
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInN1YiI6IjEiLCJpYXQiOjE2NzkzMDUzMDAsImV4cCI6MTY4MTg5NzMwMH0.wZTqM6p69J1DSrtO3bpLgc5yPVm8dWTffHTHT3lF5E8y9Qn4vK5JZeiD5yeGXxOc-FZy3cdauiZGpbCi74R4uA
