
### store movie image
POST {{protocol}}{{host}}:{{port}}/api/file-storage/movie/2872718
Authorization: Bearer {{adminToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="raw-movie-image.jpg"

< ./object-storage/raw-movie-image.jpg
--boundary--


### delete movie image
DELETE {{protocol}}{{host}}:{{port}}/api/file-storage/movie/48812
Authorization: Bearer {{adminToken}}


### store user profile photo
POST {{protocol}}{{host}}:{{port}}/api/file-storage/profile-photo
Authorization: Bearer {{userToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="image"; filename="raw-profile-photo.jpeg"

< ./object-storage/raw-profile-photo.jpeg
--boundary--


### delete user profile photo
DELETE {{protocol}}{{host}}:{{port}}/api/file-storage/profile-photo
Authorization: Bearer {{userToken}}
