
### Retrieve all movies
GET localhost:8080/movie/all
Content-Type: application/json

### Retrieve a movie by its ID
GET localhost:8080/movie/1
Content-Type: application/json

### Retrieve a list of movies by its name (case-insensitive, substring search) -> LIKE query
GET localhost:8080/movie/search-title/en
Content-Type: application/json

###
POST localhost:8080/movie/add
Content-Type: application/json

//{
//  "title": "It",
//  "year": 2017
//}

{
  "title": "The Conjuring",
  "year": 2013
}

### PUT       change property of a row/field

### Delete a movie by its ID
DELETE localhost:8080/movie/3
Content-Type: application/json
