
### Retrieve all movies
GET localhost:8080/movies
Content-Type: application/json

### Retrieve a movie by its ID
GET localhost:8080/movie/1
Content-Type: application/json

### Retrieve a movie by its exact name (case-insensitive)
GET localhost:8080/movieExactSearch?title=It
Content-Type: application/json

### Retrieve a list of movies by its name (case-insensitive, substring search) -> LIKE query
GET localhost:8080/movieSubstringSearch?title=one
Content-Type: application/json

### Retrieve a list of movies by its name (case-insensitive, similarity search, which algorithm?) -> MySQL Full-Text Search
GET localhost:8080/movieSimiliaritySearch?title=It
Content-Type: application/json

### lists of movies, pagination and

### POST
### PUT       change property of a row

### Delete a movie by its ID
DELETE localhost:8080/movie/3
Content-Type: application/json
