
### get 1 movie by id
GET {{protocol}}{{host}}:{{port}}/api/movie/2872718
Content-Type: application/json


### get multiple movies by an array of ids
POST {{protocol}}{{host}}:{{port}}/api/movie/get-movies
Content-Type: application/json

{
  "movieIds": [1457767, 1396484, 2872718]
}


### add new movie to db
POST {{protocol}}{{host}}:{{port}}/api/movie/create-movie
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIyIiwiaWF0IjoxNjY2MDY4MTYyLCJleHAiOjE2Njg2NjAxNjJ9.S1q_wUaLn5k-fWlV2GxupXSdIWmpVVRhOqXtHyJGUwALs505fYQTkffaMc4IA6Bz8wSO8npRDrQuOID8AMl_og
Content-Type: application/json

{
  "primaryTitle": "My Test Movie",
  "originalTitle": "My Test Movie",
  "startYear": 2025,
  "endYear": null,
  "runtimeMinutes": 118,
  "movieGenre": ["ANIMATION", "MYSTERY"],
  "movieType": "TV_MOVIE",
  "adult": false
}


### update existing movie
PUT {{protocol}}{{host}}:{{port}}/api/movie/21110305
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNjY0NDczODU4LCJleHAiOjE2NjcwNjU4NTh9.ETAhhVOlArJFdUVV1TsFO9xiEeUCICeorW19lZIgwtZeCS_qx_wrCL7sgcZjjrCb0IxO8pQWTvos9hXYZtF8JA
Content-Type: application/json

{
  "primaryTitle": "My Test Movie update",
  "originalTitle": "My Test Movie",
  "startYear": 2018,
  "endYear": null,
  "runtimeMinutes": 118,
  "movieGenre": ["ANIMATION", "MYSTERY"],
  "movieType": "TV_MOVIE",
  "adult": false
}


### delete movie
DELETE {{protocol}}{{host}}:{{port}}/api/movie/21110304
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI2IiwiaWF0IjoxNjY0NDczODU4LCJleHAiOjE2NjcwNjU4NTh9.ETAhhVOlArJFdUVV1TsFO9xiEeUCICeorW19lZIgwtZeCS_qx_wrCL7sgcZjjrCb0IxO8pQWTvos9hXYZtF8JA
Content-Type: application/json


### search for movie by primaryTitle
GET {{protocol}}{{host}}:{{port}}/api/movie/search/Nightcrawler?page=0&size=10
Content-Type: application/json
