
### swagger UI - exec in browser
GET {{protocol}}{{host}}:{{port}}/v3/swagger-ui.html
Content-Type: application/json


### swagger as json
GET {{protocol}}{{host}}:{{port}}/v3/api-docs
Content-Type: application/json


### download openapi-spec
GET {{protocol}}{{host}}:{{port}}/v3/api-docs.yaml
Content-Type: application/json
