### search for movies by
POST {{protocol}}{{host}}:{{port}}/api/search/movies?query=it&page=0&size=20
Content-Type: application/json

{
  "movieType": "MOVIE",
  "movieGenre": ["HORROR"],
  "minStartYear": 2010,
  "maxStartYear": 2022,
  "minRuntimeMinutes": 80,
  "maxRuntimeMinutes": 230,
  "minImdbRating": 6.3,
  "maxImdbRating": 9,
  "adult": false
}


### get multiple movies by an array of ids
POST {{protocol}}{{host}}:{{port}}/api/search/movies?query=Smultronstället&page=0&size=20
Content-Type: application/json

{}
