
### Add new user via POST
POST http://127.0.0.1:8080/auth/login
Content-Type: application/json

{
	"username":"MrBudweis123",
	"password":"123456"
}

### GET {{protocol}}{{host}}:{{port}}/users

### Add new user via POST
POST localhost:8080/addUser
Content-Type: application/json

{
  "username":"Clara",
  "email":"clara@yahoo.de",
  "password":"mynewpw"
}

### Retrieve list of all Users
GET localhost:8080/users
Content-Type: application/json

### Retrieve one db-entry by ID
GET localhost:8080/user/3
Authorization: Basic USER password
Content-Type: application/json

### update existing entry
PUT localhost:8080/updateEmail?oldEmail=jack@gmail.com&newEmail=new@web.de

### delet entry by ID
DELETE localhost:8080/deleteUserById/2
Content-Type: application/json

#### Basic authorization with variables.
#GET https://httpbin.org/basic-auth/user/passwd
#Authorization: Basic {{username}} {{password}}
