
### watch a movie
GET {{protocol}}{{host}}:{{port}}/api/watched-movie/2872718/watch
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibGVzX2dyb3NzbWFuIiwic3ViIjoiMSIsImlhdCI6MTcxMTkxMzQ1NCwiZXhwIjoxNzE0NTA1NDU0fQ.gYnFt18MWiyMnbwAZD4N1rmhr4I1MHq57LWDwdO0Sb8HbFGKvsoqfCLqxQR2J8IrlfDg5g4ELe1rJui8DBCrnA
Content-Type: application/json


### delete watched movie
DELETE {{protocol}}{{host}}:{{port}}/api/watched-movie/2872718
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sInVzZXJuYW1lIjoibGVzX2dyb3NzbWFuIiwic3ViIjoiMSIsImlhdCI6MTcxMTkxMzQ1NCwiZXhwIjoxNzE0NTA1NDU0fQ.gYnFt18MWiyMnbwAZD4N1rmhr4I1MHq57LWDwdO0Sb8HbFGKvsoqfCLqxQR2J8IrlfDg5g4ELe1rJui8DBCrnA
Content-Type: application/json
