apiVersion: v1
data:
    backend_address: ENC[AES256_GCM,data:9g4G6iF6c1XeTh2dIRTabZ40ESsFMGTaJaozywDS6IYW0FwT3CLtwMu7LyRW4FahNbyf1Di3tBk=,iv:8mOGd84Yz+2pLOywRji17/4ij8sXS7aEs5/J+Skr5+g=,tag:PowUJQy1wwOFHlKmR3oCBQ==,type:str]
    elasticsearch_password: ENC[AES256_GCM,data:GwCRi4vqafpkGcvVsqLjI49SxuyH/d/vzf6oO80gf3U=,iv:fosLXazwg4oAKSquvvVmINUbwsx5GSqfr7SJeGeMs50=,tag:sdJle7z3YIfKUjknqVTWWA==,type:str]
    elasticsearch_username: ENC[AES256_GCM,data:9AlcTyrFr5CO5prQ,iv:gXwTfVUvsblWfE0qn8rse5fnl7bAa/llOVWAjZ9UeqM=,tag:rnawOiRKr8KDwAYC8sZUGQ==,type:str]
    frontend_address: ENC[AES256_GCM,data:pABVKZmS4HII8rz2Z7gvzEDFlYbl3GE28TtLwqa9xq1JDoRv2ifZJja9OdvupcG2clxJEg==,iv:DebqSL/8n9fi9f61IxQg53U/KuXrJkt7iTJProAQliY=,tag:JP0qkjF9+1f5tmPSw6Oa6Q==,type:str]
    jwt_secret_prod: ENC[AES256_GCM,data:MycNEFhGqZLFkzppgLGR8qQ9GY+97o1P3b0pwZwlOUwkp/6E/Z/nzaPT1XAvVX/tTBimPudq2PEzz/vtvhA/yQwyLs8l5X82eCmpv8YNZUdQ9soq/EIEDRd4cu6vrzFJ2eEPOcHcKjyfm1OCxE1wD+rNHd7914a+,iv:Vt45JMPXyZqWMGnkwRHyG0N5BabSfen2jt4zWMzJpcA=,tag:NhetZVKt11oH9fiwetTMgg==,type:str]
    mail_password: ENC[AES256_GCM,data:7spwuEtNTab20dYS,iv:p9mmkZuYegnLhjQFPr1gXI95IHFBhRvhm75Y9RSdSCE=,tag:VIvzMmfKoo8/ySR9l5uj/A==,type:str]
    mail_username: ENC[AES256_GCM,data:6Jfjfzf+UFKMSNBa,iv:saAPhjUJMNWzzOhqcc+SnDFUtVybLDPH5BScQ/PJjyY=,tag:A63xW6ZfofN1TdNqsrRgxA==,type:str]
    object_storage_access_key: ENC[AES256_GCM,data:2oVADS8ZJy14iaWQ8Qs8DW8UXs4gTFfdvcb2diNoUpll9BN7wGePq/bcJ4Y=,iv:Pz0t6GTphqa5ebhBolGQDP/G2vaHIfhe0J/EyMNI1DI=,tag:CWFS3i98UL//3FxRoMpfdA==,type:str]
    object_storage_secret_key: ENC[AES256_GCM,data:nfJkbTZ7i1BZQx0CV1o11tW2uifB2MdUCDhhfMxsihK1YBok1n+2O5ARD7G1e54KOeCJwvA+AhNh7MR3ShJQGaTq8yLWUbRRdEyui9Nt5bhqEsqDv57SpA==,iv:W7ydDQoUs77EGg90hKR8C3eTaG/FRW3crBxD4Mp7qfg=,tag:Gd8Ey1vsvFMHA2Krse1nLA==,type:str]
    postgresql_password: ENC[AES256_GCM,data:yFX+Mdwyv2/oyB+o755LjdtD9Y1KjQgjEBGy2l44cxPftcWml4x05lTPvQbf33uQbGH2j3i8855Q2cmIaeOPdg==,iv:pFRqr8iXg1sFJrj+eThRZhhrDd+0zWQxnMeefewuAXo=,tag:gEAZoIsAGADEmJZPjapB8Q==,type:str]
    postgresql_username: ENC[AES256_GCM,data:QGKLudanw5qOCK8BsHCQTkFifjU=,iv:EuIOTOv5zBCSsc7OfNaoWUnDDn5hUgcC26/9Ecr2+hU=,tag:Lx7hdT6GGdbOnXnu9uxpsg==,type:str]
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: backend-runtime
    namespace: imdb-clone
stringData:
    google_client_id: ENC[AES256_GCM,data:EiD/ZRjXLtqwjex6uMoVhbhcXm77aNNfa/vAoGj8DNoUrixdYMoVnDUoOs/YiKDwYfKRd/zbwlNfnyTX2p8O2WGS1YtiK9bi,iv:lLNnv8YuLMGM3IwbfHBxvOVydRXA187Qop6D2mK88tE=,tag:bUY1lu9jiKLlXqjYmx69Dg==,type:str]
    google_client_secret: ENC[AES256_GCM,data:SCKM4ijiffKDN4mEecm7fGfgtD62FfQKW8iOUGHUWF7g7kY=,iv:feR1MYv2aaos7YPUX3ht9TzDJijiFyjP9CrBJzUfP6M=,tag:O8fPZqdQ7KNNds+5ePl8RA==,type:str]
    github_client_id: ENC[AES256_GCM,data:vKOvp5kbZePNWAyRkplafu7nhfA=,iv:iPwamgHzobUTi7mwmTOn01PaCp89SIacmS2jN5t6Puk=,tag:7+SBfRa1ne4JCtlVCnWSEQ==,type:str]
    github_client_secret: ENC[AES256_GCM,data:BT/Akd6b2JgDWk/f7PWBEji5YC2L1SBVJ8BEafMiKHp2GYhBZai5qg==,iv:ZsafCpZZLm0wMOCIS8JubC5QXLED18cXb/teMQW+lU4=,tag:epnor033yXeenUkFkbqwtg==,type:str]
    NOTIFICATION_OUTBOX_KEY: ENC[AES256_GCM,data:PxR+V+Be3C3z/6SiSl5++PDsMkvLYB/I4d4Jzyg+uyM2AlX6IocNLDV15uk=,iv:hgIYUp6Sm1RoS9eU9QqD3nm/EWvPMl4y5f47ubeFYs8=,tag:In6IDNwPjntd+U2nwUDGow==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBibXFLaEJVSTFHZHpVYWwv
            Y2lucjVIVkVYcVh0ck9OUTBCNksvZ1FEaEFBCjd0dXRxWEhPaUNQWWhIT0ZmNHlr
            ZWR6UEwvVjlzL0g2MU1QeGRoYU15dU0KLS0tIDYxS2xNZHVEVW9ndGN5REZSaGRZ
            QjR4V3FQTFlDVWxaT1ZldUZBTzJRZkkKLty51EZQF1vC3SSaGe+gp7dgWk88eJUg
            qYE1I7e6BWKgESgJSkoUf0CX7HGN+/jB+q7rhvyL09Xl8Go808M4fg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1erem2t02nlncp53ehrjjyqcwd6uhfr2vrl6saf4c53esr99vv9ms2wgpw0
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-15T14:07:04Z"
    mac: ENC[AES256_GCM,data:QXimdA9lP+ktVemWjHJDofHQMo8CXRy4R2pdPBv1p5yz9dfx30V2yKhfdrGg0exf5d7/awa7GF/87m+eLzsDXxbMLh9P3Q1CRIcqm/RcRJEmFKHhlnKo3I+CYZdiPzyvRkZg+K1lRRFeM0Oh/tnupFvkVAND3MsFmK4BzEvNj/0=,iv:R59EJNKkCYSRbeFVgex12TyV6L2qHarYGnvdvgZiX9A=,tag:tG8du5+3v9Z3YTGfxLWhxw==,type:str]
    version: 3.13.2
