apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - argocd-ingress.yaml
  - cert-manager.yaml
  - traefik-config.yaml
  - letsencrypt-cluster-issuer.yaml
  - backend-runtime.sops.yaml
  - postgresql-credentials.sops.yaml
  - rustfs-credentials.sops.yaml
  - backend.yaml
  - frontend.yaml
  - eck-operator.yaml
  - elasticsearch.yaml
  - observability-grafana-admin.sops.yaml
  - observability-grafana-viewer.sops.yaml
  - observability/dashboards
  - observability.yaml
  - ingress.yaml
  - postgresql.yaml
  - rustfs.yaml
  - rustfs-bucket-job.yaml
