apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: 7.3.0
    helm:
      releaseName: loki
      valuesObject:
        deploymentMode: SingleBinary
        loki:
          auth_enabled: false
          analytics:
            reporting_enabled: false
          commonConfig:
            path_prefix: /var/loki
            replication_factor: 1
          compactor:
            retention_enabled: true
            retention_delete_delay: 2h
            delete_request_store: filesystem
          limits_config:
            retention_period: 168h
            max_query_lookback: 168h
            max_query_length: 168h
          schemaConfig:
            configs:
              - from: "2024-01-01"
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: index_
                  period: 24h
          storage:
            type: filesystem
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            enableStatefulSetAutoDeletePVC: false
            whenDeleted: Retain
            whenScaled: Retain
            storageClass: local-path
            accessModes:
              - ReadWriteOnce
            size: 10Gi
          resources:
            requests:
              cpu: 100m
              memory: 384Mi
            limits:
              cpu: 750m
              memory: 1Gi
        read:
          replicas: 0
        write:
          replicas: 0
        backend:
          replicas: 0
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false
        serviceAccount:
          automountServiceAccountToken: false
        sidecar:
          rules:
            enabled: false
        gateway:
          enabled: true
          replicas: 1
          verboseLogging: false
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
        lokiCanary:
          enabled: true
          extraArgs:
            - "-streamname=service_name"
            - "-streamvalue=loki-canary"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 64Mi
        monitoring:
          serviceMonitor:
            enabled: true
            interval: 30s
        minio:
          enabled: false
        test:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
