apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: imdb-clone-seed
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/NiklasTiede/imdb-clone
    targetRevision: master
    path: infrastructure/clusters/home/maintenance/movie-seed
  destination:
    server: https://kubernetes.default.svc
    namespace: databases
  syncPolicy:
    automated:
      enabled: false
    syncOptions:
      - CreateNamespace=false
