apiVersion: v1
data:
    password: ENC[AES256_GCM,data:TZssS2+kAwULU3Mm1SmB2ZVHYbfe728Ocdpnm8a0NahmqNAOmB6FX/w41K5SpabZWRTGU/2djWD6XJRWcs0r1w==,iv:0qn6Ku7ISxoYnFayydsP6PEWkp8fvOaa0LWS9FOfN1A=,tag:iwsoB+dLPLRiotWnF0I5tA==,type:str]
    postgres-password: ENC[AES256_GCM,data:jCT7BY4/W5QFUEbyF/3DepaGdxxICoiXsRAmQ8oGIOshO1Kk9VCmDngc1n1BsFVSMfkDMHZOpD61+blH+hPnEQ==,iv:TZyd9UTMN+IQ5fKxpzokZZ8n9bsYXoZPe3lu19nxSNc=,tag:jwUAwoax3VqH15HpOjsYpw==,type:str]
    postgresql_password: ENC[AES256_GCM,data:vZLrOfrc6B6wY84jpQicim/RBlZenJniMbAtvek1PBxihn7ISGbs37gVpZZvvPeSnv06qwCvfYn6iKzMsdPSfA==,iv:bWJeOQ4ZzQIYBqXU9JV6fCfHO46OsMmg9DC/uku1+hA=,tag:8jac97FBAuJ02bkLgpPh8w==,type:str]
    postgresql_username: ENC[AES256_GCM,data:orn4Wlku3fVcGjAXyR1Y5lhAN3Q=,iv:CIqoAa7QJfkh6U9dD0rTaOZ8b3tyK/+MG48DRLWZ/kY=,tag:1kA0cQRhxQ2iG0ByeW+1hg==,type:str]
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: imdb-clone-postgresql
    namespace: databases
sops:
    age:
        - recipient: age1erem2t02nlncp53ehrjjyqcwd6uhfr2vrl6saf4c53esr99vv9ms2wgpw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkMkNvY3pWV0lxQ2xZWnFm
            cVZPOHlkU1pQd1ArVWIvRWM0Tk5qNmhreWxzCjl3dFhudEx4TXlDZFh1V1p1WnVC
            TmFRNFZEcTg4K2VqSW5QdXMxZHVDUFUKLS0tIEFsY1RmTWswRk9naGxBSjJyekk0
            bVJNYTNQN1p6d0dOcVFnOC91TjhuVlkK0ef5FqlC+WYN+/0xaLzrE64LEYOkyQ1j
            U9hKv8nIiWg6s7ATkVdiJNrebw9mnihq2253Xrxu2OJdLb06kKQ49A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T20:44:53Z"
    mac: ENC[AES256_GCM,data:LTmEKP8Ki6+LD1mL+3D7KdJ3azlL4D3Ttt/6Ty04wmt6hs2u77eibUixUgfQdgnZWmbKpFdK4CfDvH7Ny+V3kcMAzA+zVNPECVYPJ4xUVAWbN6RpEjF3ZZlHYtBUBI13u68XlfobEFdtVLHmZv438iCPx4AG1v0ynzCjNLr2IHc=,iv:fmCt0qxeVlEVZ3joyZrC1ofzZTIBtHhLpCo5m9EmKKE=,tag:n9sFgIr3IHHgiLQPNxEykw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
