apiVersion: v1
data:
    access_key: ENC[AES256_GCM,data:CkSMMIT+LnHrKA96yzMvJWNPtLhM8ypJuKVW8ggxaoHOEXhTf0uYp8fSUJg=,iv:IKjtEV+eRiJj4Xb+xTFlzxupxrHbWCTv2h8ew55v134=,tag:77d7PxqdyFAv8q0roLmxwA==,type:str]
    object_storage_access_key: ENC[AES256_GCM,data:xubdaTZRvPYFqj3bvz54xkaBkWfVGlKQbnJFP3GkU6/jmFkTZKLW2Q6wG7U=,iv:h11nqEZfprWPv4obp/xDKOaKaiPbY2HFnuh/lKGt3Nw=,tag:jPXZjV8MiFeUnj1hIGVZwQ==,type:str]
    object_storage_secret_key: ENC[AES256_GCM,data:YOHc74Tb9TDmrsDKCpLsrKTYSympRl5EljFoRGMDWrHkkhph2up2LpLFJDllPy/oPhCjsIvHlFzgNw/CVvbo/ZKmpRXdyrqlWJ1mRBNowXEGbZOE2c6IGw==,iv:GqJ99rAaw3upnw/X5x5MJ12UF22onFyralMV9aQoDTw=,tag:4Mcsp5wo4UkW5yetcdISOg==,type:str]
    secret_key: ENC[AES256_GCM,data:JZwfo+RjQAVukVCmG+MQ15Ulmo9lckjh1q20kjb0Qm42v7BNH+nIIJpw7Y9bZryBad4j8NJHmh0E50IfprSNF+Yhxd7u+mpgzWn/TDKaMR7YN+H0CZNdlA==,iv:vtaHn76eSKGJxML6p4XzHs5iCt6dlGD2IRWXuFj6bkY=,tag:N7PIbL3VqBS2PKPLVrmvag==,type:str]
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: imdb-clone-rustfs
    namespace: databases
sops:
    age:
        - recipient: age1erem2t02nlncp53ehrjjyqcwd6uhfr2vrl6saf4c53esr99vv9ms2wgpw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnMjRXc3U3Yk9MZzl2RUdx
            NEFWejhIcTI2NXJqRVB0VzNGeVV6eTBQL0NrClBlQUs4S3VKS0MyelIrNldSL2dU
            SlcrZDgydEE5Zkw5OWZuTjEyWDNRYVEKLS0tIDI2SXEyL3J0SkhyQk9sTWZrR3BG
            YkdMQkRIZEhnMGkzaUd3NllCRFhOOFEK8U2ElUFROiB1wKU8OkzZJJoK4aYV8RhO
            SdDG4nN0pj7Llli4phJzAQG044gkn1RrHy+LSdC0CxfJWuK1i/NzjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T21:26:45Z"
    mac: ENC[AES256_GCM,data:xBbtjvWZzOHKkPYQISZI0QnGRdZSm+nuBU7c0oUDCSCpWGFw4JW1XtQJnmTpoo2e/OhpaKCgOMYhd0H3Sr+vVYiYaTEMlk59VlRetVCmyF5XRluNf8GUqZZdp6RUZ4oaLZHx2D9O02pq9xEfNnlsWDitoOnc/H38u/QkYHmQ2z0=,iv:t+s8nlHng5wF4SjvLnwovWXe6apKAbhF6mGPvzKZ2iQ=,tag:wN7DcHfQ0Qe2i+tf7L1aBw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
