apiVersion: v1
data:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:ahFhuQKThAHYjockR66jc8y2j+D1NKOgAIWjC+6GAf4li2fvMae2XjaqpDA=,iv:OKbgJm3ByIHTOLSmh9om8BkD7T+tS7lQojHRJslrdAk=,tag:IOwaQkka2/unV+VPI0sE/g==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:2cmzjdQO3oUPGnt4Zw70u3XihMgebQSmK/xVO8YQYRx3lYWKsljXjnjVFHFzBo2QbLl2gUllvtIIrVbjp56Icf/SYx/COSV+eRV8cQmcmPqn7o02BtiszA==,iv:HdegtTjC37JU1QYt6ILxyFnWlUTD0w7Q9PZSHIPX19Y=,tag:7JPYHAS+UstKrDTRlI+8ww==,type:str]
    object_storage_access_key: ENC[AES256_GCM,data:S8jMYJYRrMZx0YKSEJMCDZ4nSDS6seAm1TR8TIPLIQ+fSAR0PGm2n1kQZSE=,iv:xgmtzqnEaEEuzby+M6Qk9pse52kP33MAr3rC1OQdVx0=,tag:P+//+4lrl4GufQvSFzsbvw==,type:str]
    object_storage_secret_key: ENC[AES256_GCM,data:ffz64vEbvs1MC5XxeFTfpgVq/NrzJCFVRw0FvGge3xXM8ymyoDp6aPnHFN8dKHppz8yyZKJpKvg3qvXG3XbjKdp71JaEM8Up3wOFFuIanc6QvLg/xVOAow==,iv:JdFsUzC9ftZ8UIAGEcMMIKEH3PnZ8vFbdUI0xKNery8=,tag:YVAuYmPeJ9lPrHAErcMvKw==,type:str]
kind: Secret
metadata:
    annotations:
        argocd.argoproj.io/sync-wave: "0"
    name: imdb-clone-rustfs
    namespace: databases
sops:
    age:
        - recipient: age1erem2t02nlncp53ehrjjyqcwd6uhfr2vrl6saf4c53esr99vv9ms2wgpw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTQS9HRGlhM3ZPMXgyWDY1
            aFJjTVdZb3ArSnR5M1pRU0phckFxaHRUc0FnCi9LUmkwZUFOUXFPQndndHA3V0t1
            WVcyYUZock8zOVg4VWs5Z3hDV2FaUDAKLS0tIHlDQzJZVUpwUDEwRnpWcEJXRFhr
            YmtWYys4SmY1S3pwTDJnbHJuZVNFbGMKOAPr+BLHqJorLctYQLZB5dkyZO+z3jd4
            OZg2P+5lxbr75Lm2NNW8oGQa9mGoLY6u1ZOnjf0tx2BUsuCMzmMaDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T21:36:26Z"
    mac: ENC[AES256_GCM,data:g0YbpK5z7s7xWVAwnRUiyuju9Hm47TXkmrT6oKVk5kaXVrX1Eefb6azxb8VgcKJTSqLr4NCLmiOj8xm6bLFyZf/NV1OTNcJPeh93uHCHz+FkvZa8ItWqR9zSh3x2r2pWjZ6KLQ530/ZcCmby3jAF1a+zO65yMMGiLGU3WrmuvPI=,iv:klNGCm2DHL4EKZ1r57O6OPu/R6BwfmUrrncHaB/eJBE=,tag:QMKovIrVe/G+nok24dk0Hg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
