apiVersion: v1
kind: Secret
metadata:
    name: sops-proof
    namespace: platform
type: Opaque
stringData:
    message: ENC[AES256_GCM,data:bFSDBMhjaeiOBOsTicUKr2B/rQT3pPGNXg==,iv:3O9LEKkGJCoGZHl1n/aZdu0/QWZkyhRO3wp2VYCOeJQ=,tag:tFiHI/7hGHEfDXnnuc8U0g==,type:str]
sops:
    age:
        - recipient: age1erem2t02nlncp53ehrjjyqcwd6uhfr2vrl6saf4c53esr99vv9ms2wgpw0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuVSswVWVqQzdMS3dTc294
            dXNvQSs0YXd5ZjN6ME9JL1QxbXlGSkxwL1NRCldpQVg0Z2VBYlgyUmdzTlpodHV5
            cTZPVENYTFdJVTZKYUZ1R3JCTGFzclUKLS0tIGU5cTQwSmNvakxoUm1FYldzSDd2
            VVJ5U0xkR054RmJqeHYrVHVNQUN1cTgKtimaSVydWWeXG0YrwfxZdlBkdBHE19dU
            p0ri1DLSSC95luh3hSqi3u03kLwlNwz7JhCZJZtmbb3QWbaL5MIU1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-17T14:34:47Z"
    mac: ENC[AES256_GCM,data:GRTTNg3UTp4pyaIXqtC+PlhzD+NKzginemqbAKkdSfbAHIjqv9LBAU1367DLdDbgwmbd/7BYGag9i0hjgfc0duXOkKJYIS7hNPhIOo9JPXHofpn/inneHHP+3wON+R+zqoVf0xOJknICQpJszhwcetydC/M0WyuribvMRLhyLDw=,iv:4ao35KsIno+O8EXzeSq9XzZShadBXKBc8ZqlGmcYGdM=,tag:sXMKJLys/PS/B7+n51IWfg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.1
