apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  valuesContent: |-
    service:
      externalTrafficPolicy: Local
