global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:

  - job_name: 'imdb_clone_backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['imdb-clone-backend:8081']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

#  - job_name: 'cadvisor'
#    scrape_interval: 5s
#    static_configs:
#      - targets: ['cadvisor:8080']
