package com.thecodinglab.imdbclone.identity.internal.security.audit;

public enum SecurityAuditEventType {
  PASSWORD_LOGIN_SUCCESS,
  PASSWORD_LOGIN_FAILURE,
  OAUTH2_LOGIN_SUCCESS,
  OAUTH2_LOGIN_FAILURE,
  PASSKEY_LOGIN_SUCCESS,
  PASSKEY_LOGIN_FAILURE,
  LOGOUT_SUCCESS,
  LOCAL_CREDENTIAL_CREATED,
  LOCAL_CREDENTIAL_PASSWORD_CHANGED,
  VERIFICATION_TOKEN_ISSUED,
  VERIFICATION_TOKEN_CONSUMED,
  PASSWORD_RESET_TOKEN_ISSUED,
  PASSWORD_RESET_TOKEN_CONSUMED,
  SOCIAL_PROVIDER_LINKED,
  SOCIAL_PROVIDER_LINK_FAILED,
  PASSKEY_REGISTERED,
  PASSKEY_DELETED,
  RATE_LIMIT_REJECTED
}
