package com.thecodinglab.imdbclone.identity.internal.security.audit;

public enum SecurityAuditEventType {
  LOCAL_CREDENTIAL_CREATED,
  LOCAL_CREDENTIAL_PASSWORD_CHANGED,
  VERIFICATION_TOKEN_ISSUED,
  VERIFICATION_TOKEN_CONSUMED,
  PASSWORD_RESET_TOKEN_ISSUED,
  PASSWORD_RESET_TOKEN_CONSUMED,
  SOCIAL_PROVIDER_LINKED,
  SOCIAL_PROVIDER_LINK_FAILED,
  PASSKEY_REGISTERED,
  PASSKEY_DELETED
}
