---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: popcorn-society-concierge-public
  namespace: imdb-clone
  annotations:
    argocd.argoproj.io/sync-wave: '7'
    traefik.ingress.kubernetes.io/router.middlewares: imdb-clone-imdb-clone-concierge-rate-limit@kubernetescrd,imdb-clone-imdb-clone-concierge-inflight@kubernetescrd,imdb-clone-imdb-clone-concierge-strip-prefix@kubernetescrd,imdb-clone-imdb-clone-security-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - popcornsociety.app
    secretName: popcorn-society-public-tls
  rules:
  - host: popcornsociety.app
    http:
      paths:
      - path: "/concierge-api/v1"
        pathType: Prefix
        backend:
          service:
            name: imdb-clone-agent
            port:
              name: http
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: popcorn-society-public
  namespace: imdb-clone
  annotations:
    argocd.argoproj.io/sync-wave: '7'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: imdb-clone-imdb-clone-public-rate-limit@kubernetescrd,imdb-clone-imdb-clone-security-headers@kubernetescrd,imdb-clone-popcorn-society-preview@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - popcornsociety.app
    - www.popcornsociety.app
    secretName: popcorn-society-public-tls
  rules:
  - host: popcornsociety.app
    http:
      paths:
      - path: "/api"
        pathType: Prefix
        backend:
          service:
            name: imdb-clone-backend
            port:
              name: http
      - path: "/oauth2"
        pathType: Prefix
        backend:
          service:
            name: imdb-clone-backend
            port:
              name: http
      - path: "/login/oauth2"
        pathType: Prefix
        backend:
          service:
            name: imdb-clone-backend
            port:
              name: http
      - path: "/webauthn"
        pathType: Prefix
        backend:
          service:
            name: imdb-clone-backend
            port:
              name: http
      - path: "/login/webauthn"
        pathType: Prefix
        backend:
          service:
            name: imdb-clone-backend
            port:
              name: http
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: imdb-clone-frontend
            port:
              name: http
