@startuml


skinparam linetype polyline
skinparam linetype ortho

hide circle
class Movie {
  - id \t\t\t\t long
  - primaryTitle \t\t String
  - originalTitle \t\t String
  - startYear \t\t\t int
  - endYear \t\t\t int
  - runtimeMinutes \t int
  - genre \t\t\t MovieGenreEnum
  - movieType \t\t MovieTypeEnum
  - adult \t\t\t boolean
  - imdbRating \t\t float
  - imdbRatingCount \t int
  - rating \t\t\t float
  - ratingCount \t\t int
  - description \t\t String
  - imageUrlToken \t String
}

class Account {
  - id \t\t\t\t long
  - username \t\t String
  - email \t\t\t String
  - password \t\t String
  - firstName \t\t\t String
  - lastName \t\t\t String
  - bio \t\t\t\t String
  - phone \t\t\t String
  - birthday \t\t\t Date
  - imageUrlToken \t String
}

class Rating {
  - movieId \t\t long
  - accountId \t long
  - rating \t\t float
}

class Comment {
  - id \t\t\t\t long
  - message \t\t\t String
  - accountId \t\t long
  - movieId \t\t\t long
}

class Watchlist {
  - accountId \t long
  - movieId \t\t long
}

class Role {
  - id \t\t long
  - name \t RoleNameEnum
}

class AccountRoles {
  - accountId \t\t long
  - roleId \t\t\t long
}


class VerificationToken {
  - id \t\t\t\t\t long
  - verificationType \t\t VerTypeEnum
  - token \t\t\t\t String
  - expiryDateInUtc \t\t Instant
  - confirmedAtInUtc \t\t Instant
  - accountId \t\t\t long
}

Account ||-down-|{ Rating
Account ||-left-|{ Watchlist
Account ||-right-|{ Comment
Account ||-right-|{ AccountRoles
Role ||-right-|{ AccountRoles
Account ||-right-|{ VerificationToken
Movie ||-down-|{ Comment
Movie ||-up-|{ Watchlist

@enduml