create table movie (
    id bigint generated by default as identity,
    imdb_id varchar(20),
    tmdb_id bigint,
    movie_type varchar(50),
    primary_title varchar(1000),
    original_title varchar(1000),
    adult boolean,
    start_year int,
    end_year int,
    runtime_minutes int,
    movie_genre bigint,
    imdb_rating real,
    imdb_rating_count int,
    description text,
    poster_image_token varchar(255),
    backdrop_image_token varchar(255),
    trailer_youtube_key varchar(255),
    rating numeric(3,1),
    rating_count int not null default 0,
    rating_sum numeric(19,1) not null default 0.0,
    created_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    modified_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    primary key (id),
    unique (imdb_id),
    unique (tmdb_id)
);

comment on column movie.id is
    'Internal application movie id. External source ids live in imdb_id and tmdb_id.';
comment on column movie.imdb_id is
    'IMDb title id including the tt prefix, for example tt3235888.';
comment on column movie.tmdb_id is
    'TMDB movie id when the title has been enriched from TMDB.';
comment on column movie.movie_genre is
    'Bitmask of MovieGenreEnum values, not a foreign key.';
comment on column movie.movie_type is
    'MovieTypeEnum name stored as text to avoid enum ordinal drift.';
comment on column movie.poster_image_token is
    'Object Storage object-name token used to derive poster image object keys.';
comment on column movie.backdrop_image_token is
    'Object Storage object-name token used to derive backdrop image object keys.';
comment on column movie.rating_sum is
    'Exact sum of app user ratings used to maintain the average rating.';

create table account (
    id bigint generated by default as identity,
    username varchar(255) unique not null,
    email varchar(255) unique not null,
    password varchar(255) not null,
    first_name varchar(255),
    last_name varchar(255),
    bio text,
    phone varchar(20),
    birthday date,
    image_url_token varchar(255),
    created_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    modified_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    locked boolean not null,
    enabled boolean not null,
    primary key (id)
);

comment on column account.image_url_token is
    'Object Storage object-name token used to derive profile image object keys.';

create table role (
    id bigint generated by default as identity,
    name varchar(255) unique not null,
    created_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    primary key (id)
);

comment on table role is 'Table storing roles available in the system.';

create table account_roles (
    account_id bigint not null,
    roles_id bigint not null,
    created_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    primary key (account_id, roles_id),
    constraint fk_account_roles_role foreign key (roles_id)
        references role(id)
        on delete cascade,
    constraint fk_account_roles_account foreign key (account_id)
        references account(id)
        on delete cascade
);

create index idx_account_roles_roles_id on account_roles (roles_id);

create table rating (
    movie_id bigint not null,
    account_id bigint not null,
    rating numeric(3,1) not null,
    created_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    modified_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    primary key (movie_id, account_id),
    constraint fk_rating_movie foreign key (movie_id)
        references movie(id)
        on delete cascade,
    constraint fk_rating_account foreign key (account_id)
        references account(id)
        on delete cascade
);

comment on table rating is 'User ratings; one rating per account and movie.';

create index idx_rating_account_id on rating (account_id);

create table watched_movie (
    movie_id bigint not null,
    account_id bigint not null,
    created_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    primary key (movie_id, account_id),
    constraint fk_watched_movie_movie foreign key (movie_id)
        references movie(id)
        on delete cascade,
    constraint fk_watched_movie_account foreign key (account_id)
        references account(id)
        on delete cascade
);

comment on table watched_movie is 'Movies marked as watched by users.';

create index idx_watched_movie_movie_id on watched_movie (movie_id);
create index idx_watched_movie_account_id on watched_movie (account_id);

create table comment (
    id bigint generated by default as identity,
    movie_id bigint not null,
    account_id bigint not null,
    message text not null,
    created_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    modified_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    primary key (id),
    constraint fk_comment_movie foreign key (movie_id)
        references movie(id)
        on delete cascade,
    constraint fk_comment_account foreign key (account_id)
        references account(id)
        on delete cascade
);

create index idx_comment_movie_id_created_at_in_utc on comment (movie_id, created_at_in_utc);
create index idx_comment_account_id_created_at_in_utc on comment (account_id, created_at_in_utc);

create table verification_token (
    id bigint generated by default as identity,
    account_id bigint not null,
    verification_type varchar(100) not null,
    token varchar(36) not null,
    expiry_date_in_utc timestamp(6) with time zone not null,
    confirmed_at_in_utc timestamp(6) with time zone,
    primary key (id),
    constraint fk_verification_token_account foreign key (account_id)
        references account(id)
        on delete cascade
);

comment on table verification_token is 'Verification and password-reset tokens issued to accounts.';

create index idx_verification_token_account_id on verification_token (account_id);

create table scheduled_tasks (
    task_name varchar(100) not null,
    task_instance varchar(100) not null,
    task_data bytea,
    execution_time timestamp(6) with time zone not null,
    picked boolean not null,
    picked_by varchar(50),
    last_success timestamp(6) with time zone null,
    last_failure timestamp(6) with time zone null,
    consecutive_failures int,
    last_heartbeat timestamp(6) with time zone null,
    version bigint not null,
    priority smallint,
    primary key (task_name, task_instance)
);

comment on table scheduled_tasks is 'Durable db-scheduler task executions.';

create index execution_time_idx on scheduled_tasks (execution_time);
create index last_heartbeat_idx on scheduled_tasks (last_heartbeat);
create index priority_execution_time_idx on scheduled_tasks (priority desc, execution_time asc);

insert into role (id, name) values
    (1, 'ROLE_ADMIN'),
    (2, 'ROLE_USER')
on conflict (id) do update
set name = excluded.name;

select setval(pg_get_serial_sequence('role', 'id'), (select max(id) from role));
