create table local_credential (
    id bigint generated by default as identity,
    account_id bigint not null,
    password_hash varchar(255) not null,
    created_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    modified_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    last_password_change_at timestamp(6) with time zone,
    primary key (id),
    constraint local_credential_account_unique unique (account_id),
    constraint fk_local_credential_account foreign key (account_id)
        references account(id)
        on delete cascade
);

create index local_credential_account_id_idx on local_credential(account_id);

insert into local_credential(account_id, password_hash, created_at_in_utc, modified_at_in_utc)
select id, password, current_timestamp, current_timestamp
from account
where password is not null;

alter table account alter column password drop not null;

alter table verification_token add column token_hash varchar(128);
alter table verification_token add column consumed_at_in_utc timestamp(6) with time zone;
alter table verification_token alter column token drop not null;

create unique index verification_token_token_hash_key on verification_token(token_hash);

create table security_audit_event (
    id bigint generated by default as identity,
    occurred_at timestamp(6) with time zone not null default current_timestamp,
    event_type varchar(100) not null,
    principal varchar(255),
    account_id bigint,
    ip_address varchar(100),
    details jsonb not null default '{}'::jsonb,
    primary key (id),
    constraint fk_security_audit_event_account foreign key (account_id)
        references account(id)
        on delete set null
);

create index security_audit_event_occurred_at_idx on security_audit_event(occurred_at);
create index security_audit_event_event_type_idx on security_audit_event(event_type);
create index security_audit_event_account_id_idx on security_audit_event(account_id);
