create table account_identity_provider (
    id bigint generated by default as identity,
    account_id bigint not null,
    provider varchar(50) not null,
    provider_user_id varchar(255) not null,
    email varchar(255),
    created_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    modified_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    primary key (id),
    constraint account_identity_provider_provider_user_unique unique (provider, provider_user_id),
    constraint fk_account_identity_provider_account foreign key (account_id)
        references account(id)
        on delete cascade
);

create index account_identity_provider_account_id_idx on account_identity_provider(account_id);
