create table discovery_event (
    id bigint generated by default as identity,
    event_id varchar(128) not null,
    event_type varchar(40) not null,
    session_hash char(64) not null,
    feed_instance_hash char(64) not null,
    section_id varchar(120) not null,
    position int,
    movie_id bigint,
    account_id bigint,
    strategy_version varchar(80) not null,
    created_at_in_utc timestamp(6) with time zone not null default current_timestamp,
    primary key (id),
    constraint uk_discovery_event_event_id unique (event_id),
    constraint fk_discovery_event_movie foreign key (movie_id) references movie(id) on delete set null,
    constraint fk_discovery_event_account foreign key (account_id) references account(id) on delete set null
);

comment on table discovery_event is
    'Privacy-aware discovery telemetry. Session and feed identifiers are SHA-256 hashes; raw browser ids are never persisted.';

create index idx_discovery_event_created_at_in_utc on discovery_event (created_at_in_utc);
create index idx_discovery_event_type_created_at_in_utc on discovery_event (event_type, created_at_in_utc);
create index idx_discovery_event_movie_id on discovery_event (movie_id);
