#!/usr/bin/env python3
import argparse
import csv
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

try:
    import boto3
except ImportError:  # pragma: no cover - installed in the seed image
    boto3 = None

try:
    import psycopg
except ImportError:  # pragma: no cover - installed in the seed image
    psycopg = None


SEED_ROOT = Path(os.environ.get("SEED_ROOT", "/seed"))
CSV_PATH = SEED_ROOT / "movie_enriched.csv"
MEDIA_ROOT = SEED_ROOT / "media" / "movies"


@dataclass(frozen=True)
class Config:
    postgres_host: str
    postgres_port: str
    postgres_db: str
    postgres_user: str
    postgres_password: str
    rustfs_endpoint: str
    rustfs_access_key: str
    rustfs_secret_key: str
    rustfs_bucket: str
    seed_name: str
    seed_version: str

    @classmethod
    def from_env(cls) -> "Config":
        return cls(
            postgres_host=require_env("POSTGRES_HOST"),
            postgres_port=os.environ.get("POSTGRES_PORT", "5432"),
            postgres_db=require_env("POSTGRES_DB"),
            postgres_user=require_env("POSTGRES_USER"),
            postgres_password=require_env("POSTGRES_PASSWORD"),
            rustfs_endpoint=require_env("RUSTFS_ENDPOINT"),
            rustfs_access_key=require_env("RUSTFS_ACCESS_KEY"),
            rustfs_secret_key=require_env("RUSTFS_SECRET_KEY"),
            rustfs_bucket=os.environ.get("RUSTFS_BUCKET", "imdb-clone"),
            seed_name=os.environ.get("SEED_NAME", "local"),
            seed_version=os.environ.get("SEED_VERSION", "local"),
        )

    def postgres_dsn(self) -> str:
        return (
            f"host={self.postgres_host} port={self.postgres_port} "
            f"dbname={self.postgres_db} user={self.postgres_user} "
            f"password={self.postgres_password}"
        )


def require_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise SystemExit(f"Missing required environment variable: {name}")
    return value


def normalize_db_value(value: str) -> str | None:
    return None if value == "\\N" or value == "" else value


def create_seed_run_table_sql() -> str:
    return """
    create table if not exists movie_seed_run (
        id bigint generated by default as identity primary key,
        seed_name varchar(100) not null,
        seed_version varchar(100) not null,
        command varchar(20) not null,
        status varchar(20) not null,
        row_count int not null default 0,
        media_count int not null default 0,
        error_message text,
        started_at_in_utc timestamp(6) with time zone not null default current_timestamp,
        finished_at_in_utc timestamp(6) with time zone
    )
    """


def staging_table_sql() -> str:
    return """
    create temporary table movie_seed_staging (
        id bigint,
        imdb_id varchar(20),
        movie_type varchar(50),
        primary_title varchar(1000),
        original_title varchar(1000),
        adult boolean,
        start_year int,
        end_year int,
        runtime_minutes int,
        movie_genre bigint,
        imdb_rating real,
        imdb_rating_count int,
        tmdb_id bigint,
        description text,
        poster_path text,
        backdrop_path text,
        trailer_youtube_key varchar(255),
        poster_image_token varchar(255),
        backdrop_image_token varchar(255)
    ) on commit drop
    """


def upsert_movie_sql() -> str:
    return """
    insert into movie (
        imdb_id,
        tmdb_id,
        movie_type,
        primary_title,
        original_title,
        adult,
        start_year,
        end_year,
        runtime_minutes,
        movie_genre,
        imdb_rating,
        imdb_rating_count,
        description,
        poster_image_token,
        backdrop_image_token,
        trailer_youtube_key
    )
    select
        imdb_id,
        tmdb_id,
        movie_type,
        primary_title,
        original_title,
        adult,
        start_year,
        end_year,
        runtime_minutes,
        movie_genre,
        imdb_rating,
        imdb_rating_count,
        description,
        poster_image_token,
        backdrop_image_token,
        trailer_youtube_key
    from movie_seed_staging
    on conflict (imdb_id) do update
    set tmdb_id = excluded.tmdb_id,
        movie_type = excluded.movie_type,
        primary_title = excluded.primary_title,
        original_title = excluded.original_title,
        adult = excluded.adult,
        start_year = excluded.start_year,
        end_year = excluded.end_year,
        runtime_minutes = excluded.runtime_minutes,
        movie_genre = excluded.movie_genre,
        imdb_rating = excluded.imdb_rating,
        imdb_rating_count = excluded.imdb_rating_count,
        description = excluded.description,
        poster_image_token = excluded.poster_image_token,
        backdrop_image_token = excluded.backdrop_image_token,
        trailer_youtube_key = excluded.trailer_youtube_key,
        modified_at_in_utc = current_timestamp
    """


def load_csv_rows(csv_path: Path) -> list[dict[str, str | None]]:
    with csv_path.open(encoding="utf-8", newline="") as file:
        return [
            {key: normalize_db_value(value) for key, value in row.items()}
            for row in csv.DictReader(file)
        ]


def start_seed_run(connection, config: Config, command: str) -> int:
    with connection.cursor() as cursor:
        cursor.execute(create_seed_run_table_sql())
        cursor.execute(
            """
            insert into movie_seed_run (seed_name, seed_version, command, status)
            values (%s, %s, %s, 'RUNNING')
            returning id
            """,
            (config.seed_name, config.seed_version, command),
        )
        return cursor.fetchone()[0]


def finish_seed_run(
    connection,
    run_id: int,
    status: str,
    row_count: int,
    media_count: int,
    error: str | None = None,
) -> None:
    with connection.cursor() as cursor:
        cursor.execute(
            """
            update movie_seed_run
            set status = %s,
                row_count = %s,
                media_count = %s,
                error_message = %s,
                finished_at_in_utc = current_timestamp
            where id = %s
            """,
            (status, row_count, media_count, error, run_id),
        )


def require_psycopg():
    if psycopg is None:
        raise SystemExit("psycopg is required to seed PostgreSQL")
    return psycopg


def seed_db(config: Config) -> int:
    psycopg_module = require_psycopg()
    rows = load_csv_rows(CSV_PATH)
    with psycopg_module.connect(config.postgres_dsn()) as connection:
        run_id = start_seed_run(connection, config, "db")
        connection.commit()
        try:
            with connection.transaction():
                with connection.cursor() as cursor:
                    cursor.execute(staging_table_sql())
                    with cursor.copy(
                        "copy movie_seed_staging from stdin with "
                        "(format csv, header true, null '\\N')"
                    ) as copy:
                        with CSV_PATH.open(encoding="utf-8", newline="") as file:
                            for line in file:
                                copy.write(line)
                    cursor.execute(upsert_movie_sql())
            finish_seed_run(connection, run_id, "SUCCEEDED", len(rows), 0)
            connection.commit()
            return len(rows)
        except Exception as exc:
            connection.rollback()
            finish_seed_run(connection, run_id, "FAILED", 0, 0, str(exc))
            connection.commit()
            raise


def build_media_key(kind_dir: str, filename: str) -> str:
    return f"movies/{kind_dir}/{filename}"


def iter_media_files() -> Iterable[tuple[str, Path]]:
    for kind_dir in ("posters", "backdrops"):
        directory = MEDIA_ROOT / kind_dir
        if not directory.exists():
            continue
        for path in sorted(directory.glob("*.webp")):
            yield build_media_key(kind_dir, path.name), path


def require_boto3():
    if boto3 is None:
        raise SystemExit("boto3 is required to seed RustFS media")
    return boto3


def seed_media(config: Config) -> int:
    boto3_module = require_boto3()
    psycopg_module = require_psycopg()
    client = boto3_module.client(
        "s3",
        endpoint_url=config.rustfs_endpoint,
        aws_access_key_id=config.rustfs_access_key,
        aws_secret_access_key=config.rustfs_secret_key,
    )
    with psycopg_module.connect(config.postgres_dsn()) as connection:
        run_id = start_seed_run(connection, config, "media")
        connection.commit()
        uploaded = 0
        try:
            ensure_bucket(client, config.rustfs_bucket)
            for key, path in iter_media_files():
                client.upload_file(
                    str(path),
                    config.rustfs_bucket,
                    key,
                    ExtraArgs={"ContentType": "image/webp"},
                )
                uploaded += 1
            finish_seed_run(connection, run_id, "SUCCEEDED", 0, uploaded)
            connection.commit()
            return uploaded
        except Exception as exc:
            connection.rollback()
            finish_seed_run(connection, run_id, "FAILED", 0, uploaded, str(exc))
            connection.commit()
            raise


def ensure_bucket(client, bucket: str) -> None:
    existing = [item["Name"] for item in client.list_buckets().get("Buckets", [])]
    if bucket not in existing:
        client.create_bucket(Bucket=bucket)
    client.put_bucket_policy(
        Bucket=bucket,
        Policy=f"""
        {{
          "Version": "2012-10-17",
          "Statement": [
            {{
              "Effect": "Allow",
              "Principal": "*",
              "Action": ["s3:GetObject"],
              "Resource": ["arn:aws:s3:::{bucket}/movies/*"]
            }}
          ]
        }}
        """,
    )


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Seed imdb-clone data and media.")
    parser.add_argument("command", choices=("all", "db", "media"))
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    config = Config.from_env()
    if args.command in ("all", "db"):
        rows = seed_db(config)
        print(f"Seeded {rows} movie rows")
    if args.command in ("all", "media"):
        objects = seed_media(config)
        print(f"Seeded {objects} media objects")


if __name__ == "__main__":
    main()
