{
 "title": "Infrastructure",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Server Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage of the hexa-core Ryzen 5 5626u",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "100 * (sum(irate(node_cpu_seconds_total{job=\"node-exporter\", mode!=\"idle\"}[5m])) / count(node_cpu_seconds_total{mode=\"system\"}))",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Usage of memory (RAM): 32Gb's are available",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "description": "Usage of NVME SSD 500GB, only 100Gb on filesystem (~370Gb are unallocated, existing volume can still be extended by this)",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_filesystem_free_bytes{mountpoint=\"/\"} / node_filesystem_size_bytes{mountpoint=\"/\"})) * 100"
    }
   ]
  },
  {
   "title": "Docker Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true
  },
  {
   "title": "Traefik Reverse Proxy",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true
  },
  {
   "title": "MySQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true
  },
  {
   "title": "Elasticsearch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true
  },
  {
   "title": "RustFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true
  },
  {
   "title": "Grafana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Prometheus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true
  }
 ]
}